source 'https://rubygems.org'
ruby '2.3.0'

gem 'autoprefixer-rails'
gem 'font-awesome-sass'
gem 'jekyll', '>= 3.0.2'
gem 'jekyll-assets', '>= 2.2.0'
gem 'jekyll-sitemap'
gem 'kramdown'
gem 'puma'
gem 'rack-jekyll', '>= 0.5.0'
gem 'rake'
gem 'sprockets-es6', '>= 0.9.0'
