source 'https://rubygems.org'
ruby '2.3.0'

gem 'autoprefixer-rails'
gem 'font-awesome-sass'
gem 'jekyll'
gem 'jekyll-assets', '>= 2.1.0'
gem 'jekyll-sitemap'
gem 'kramdown'
gem 'puma'
gem 'rack-jekyll'
gem 'rake'
gem 'sprockets-es6', '>= 0.9.0'
